services:
  ljx-booking-app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "3000:3000"  # Frontend
      - "3001:3001"  # Backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=/app/data/database.sqlite
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  data:
    driver: local
  logs:
    driver: local 